### ISSUE TITLE
Copyfile error

### ISSUE THREAD

**Issue by Zaista** [sorry-cypress/cy2#17]
cy2 seems to have some access errors using latest cypress v9.0.0:
Error: EACCES: permission denied, copyfile '/root/.cache/Cypress/9.0.0/Cypress/resources/app/packages/server/config/app.yml' -> '/root/.cache/Cypress/9.0.0/Cypress/resources/app/packages/server/config/_app.yml'
13:13:12       at Object.copyFileSync (node:fs:2790:3)
13:13:12       at Object.exports.patch (/e2e/node_modules/cy2/lib/patch.js:18:8)
13:13:12       at async Object.exports.run (/e2e/node_modules/cy2/index.js:8:3) {
13:13:12     errno: -13,
13:13:12     syscall: 'copyfile',
13:13:12     code: 'EACCES',
13:13:12     path: '/root/.cache/Cypress/9.0.0/Cypress/resources/app/packages/server/config/app.yml',
13:13:12     dest: '/root/.cache/Cypress/9.0.0/Cypress/resources/app/packages/server/config/_app.yml'

cy2: v1.3.0
cypress: v9.0.0
sorry-cypress: v1.1.1
teamcity + docker (using volumes on teamcity agents)

works fine with cypress v8.7.0 tho

**Comment by agoldis** [comment]
No permissions to write files to `/root` with the user that's running `cy2`. 

Few options here:
- change cypress install directory with user access
- chmod to `/root/.cache/Cypress`
- run `cy2` with `sudo`

**Comment by antonkad** [comment]
I'm facing the same problem. Willing to run cy2 in a docker container through a k8s cronJob. I get this error

` ~/test-cypress $ docker run -it  --entrypoint /bin/sh -v $PWD:/e2e -w /e2e stockiteasy-e2e:1.0
# npx cy2
Error: ENOENT: no such file or directory, copyfile '/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/config/app.yml' -> '/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/config/_app.yml'
    at Object.copyFileSync (fs.js:1991:3)
    at Object.exports.patch (/e2e/node_modules/cy2/lib/patch.js:18:8)
    at async Object.exports.run (/e2e/node_modules/cy2/index.js:8:3) {
  errno: -2,
  syscall: 'copyfile',
  code: 'ENOENT',
  path: '/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/config/app.yml',
  dest: '/root/.cache/Cypress/8.6.0/Cypress/resources/app/packages/server/config/_app.yml'
}`

At the moment my Dockerfile is plain simple:

`FROM cypress/included:8.6.0

WORKDIR /e2e
RUN npm -g  install cy2`

I figured that I absolutly need to have the 8.6.0 version in order to make the command  `npx cy2` run. Is this normal ? How do I use more recent versions of cypress ?

regards

**Comment by Zaista** [comment]
I "solved" the problem by simply not using volumes, and copying everything you would use from volumes directly into the container. This way it works, no idea why tho.

**Comment by agoldis** [comment]
@antonkad I'd recommend extending the installing cypress on project level, instead of using the globally installed package.

Switching cypress API requests destination requires replacing config file. Depending on container fs permissions it may not be able to change the config file.
